### ISSUE TITLE
Make this plugin 0.5.0 compatible

### ISSUE THREAD

**Issue by achambers** [treyhunner/ember-deploy-ssh-index#20]
Hi,

Aaron from the [ember-cli-deploy](https://github.com/ember-cli/ember-cli-deploy) team here.

We're in the process of getting things ready for our 0.5.0 release of ember-cli-deploy which is quite a shift away from how the addon currently works. With this change comes the need to make sure existing ember-cli-deploy plugins (this is the new name for them, as opposed to adapters) are compatible with the new version.

Are you in a position to make a 0.5.0 compatible version of this plugin? Or to update this one?

I'm am more than happy to help out or guide you along the way if needed.

Please get in touch and let me know if this is something you're able to help with, or if you need any help in doing so.

Cheers,
Aaron

**Comment by treyhunner** [comment]
Hi @achambers!  Unfortunately I do not plan to do development on this project anytime soon because I have no active Ember projects right now and therefore have little personal need for this.  _I should probably update the README file to note this._

However, I would gladly merge a pull request to update this project to 0.5.0 compatibility.

By the way, I think it's great that you're reaching out like this. :+1:

**Comment by livkiss** [comment]
@achambers I started using this adapter for a project of mine, so I would definitely be interested in supporting a new release of ember-cli-deploy.

I tried to look around [ember-cli/ember-cli-deploy](https://github.com/ember-cli/ember-cli-deploy) but couldn't find really good information about the API changes. Can you please provide me with more information?

edit: I found some [upgrade instructions](https://github.com/ember-cli/ember-cli-deploy/pull/189/files?short_path=afd753c#diff-afd753cd2656cb793ce24fe18bb4aea0). Anything else?
edit2: Just found the v0.5.x docs :+1: http://ember-cli.github.io/ember-cli-deploy/docs/v0.5.x/

**Comment by arenoir** [comment]
I am working on a [plugin](https://github.com/arenoir/ember-cli-deploy-ssh2) that works over ssh.  The primary difference is that it is designed to work with multiple application files thus all files are within a folder named by `revisionKey`.  I also intend to be able to handle the assets as well hence the name.

**Comment by varoot** [comment]
This should be resolved by #24 already

**Comment by treyhunner** [comment]
@varoot thanks!
